export const productsSeedData = [
  // OTC Medicines
  { name: 'Napa 500mg', slug: 'napa-500mg', genericName: 'Paracetamol', brand: 'Beximco', manufacturer: 'Beximco Pharmaceuticals', category: 'otc-medicines', dosageForm: 'TABLET', strength: '500mg', packSize: '10 tablets/strip', price: 18, discountPrice: 15, stockQty: 500, isPrescriptionRequired: false, isFeatured: true, shortDescription: 'Paracetamol 500mg for fever and mild pain relief', tags: ['fever', 'pain', 'headache', 'paracetamol'] },
  { name: 'Napa Extra', slug: 'napa-extra', genericName: 'Paracetamol + Caffeine', brand: 'Beximco', manufacturer: 'Beximco Pharmaceuticals', category: 'otc-medicines', dosageForm: 'TABLET', strength: '500mg + 65mg', packSize: '10 tablets/strip', price: 30, stockQty: 300, isPrescriptionRequired: false, isFeatured: true, shortDescription: 'Enhanced pain relief with caffeine', tags: ['pain', 'headache', 'migraine'] },
  { name: 'Ace 500mg', slug: 'ace-500mg', genericName: 'Paracetamol', brand: 'Square', manufacturer: 'Square Pharmaceuticals', category: 'otc-medicines', dosageForm: 'TABLET', strength: '500mg', packSize: '10 tablets/strip', price: 18, stockQty: 400, isPrescriptionRequired: false, isFeatured: false, shortDescription: 'Paracetamol 500mg tablet for pain and fever', tags: ['fever', 'pain', 'paracetamol'] },
  { name: 'Histacin 4mg', slug: 'histacin-4mg', genericName: 'Chlorpheniramine Maleate', brand: 'Square', manufacturer: 'Square Pharmaceuticals', category: 'otc-medicines', dosageForm: 'TABLET', strength: '4mg', packSize: '10 tablets/strip', price: 12, stockQty: 200, isPrescriptionRequired: false, isFeatured: false, shortDescription: 'Antihistamine for allergy relief', tags: ['allergy', 'antihistamine', 'cold'] },
  { name: 'Fexofenadine 120mg (Fexo)', slug: 'fexo-120mg', genericName: 'Fexofenadine', brand: 'Square', manufacturer: 'Square Pharmaceuticals', category: 'otc-medicines', dosageForm: 'TABLET', strength: '120mg', packSize: '10 tablets', price: 70, stockQty: 280, isPrescriptionRequired: false, isFeatured: true, shortDescription: 'Non-drowsy antihistamine for allergies', tags: ['allergy', 'antihistamine'] },
  { name: 'ORSaline-N', slug: 'orsaline-n', genericName: 'Oral Rehydration Salt', brand: 'Renata', manufacturer: 'Renata Limited', category: 'otc-medicines', dosageForm: 'POWDER', strength: '20.5g', packSize: '20 sachets', price: 90, discountPrice: 80, stockQty: 600, isPrescriptionRequired: false, isFeatured: true, shortDescription: 'Oral rehydration solution for diarrhea', tags: ['ors', 'diarrhea', 'rehydration'] },
  { name: 'Antacid Plus', slug: 'antacid-plus', genericName: 'Aluminium Hydroxide + Magnesium Hydroxide', brand: 'Renata', manufacturer: 'Renata Limited', category: 'otc-medicines', dosageForm: 'SUSPENSION', strength: '200ml', packSize: '200ml bottle', price: 80, stockQty: 150, isPrescriptionRequired: false, isFeatured: false, shortDescription: 'Antacid suspension for heartburn and acidity', tags: ['antacid', 'gastric', 'acidity'] },
  { name: 'Neotack 150mg', slug: 'neotack-150', genericName: 'Ranitidine', brand: 'Square', manufacturer: 'Square Pharmaceuticals', category: 'otc-medicines', dosageForm: 'TABLET', strength: '150mg', packSize: '10 tablets', price: 22, stockQty: 400, isPrescriptionRequired: false, isFeatured: false, shortDescription: 'H2 blocker for acidity relief', tags: ['acidity', 'heartburn'] },

  // Prescription Medicines
  { name: 'Seclo 20mg', slug: 'seclo-20mg', genericName: 'Omeprazole', brand: 'Square', manufacturer: 'Square Pharmaceuticals', category: 'prescription-medicines', dosageForm: 'CAPSULE', strength: '20mg', packSize: '14 capsules', price: 98, discountPrice: 85, stockQty: 250, isPrescriptionRequired: true, isFeatured: true, shortDescription: 'Proton pump inhibitor for acid reflux and ulcers', tags: ['ulcer', 'gastric', 'gerd'] },
  { name: 'Monas 10mg', slug: 'monas-10mg', genericName: 'Montelukast', brand: 'Square', manufacturer: 'Square Pharmaceuticals', category: 'prescription-medicines', dosageForm: 'TABLET', strength: '10mg', packSize: '10 tablets', price: 120, stockQty: 180, isPrescriptionRequired: true, isFeatured: false, shortDescription: 'Leukotriene receptor antagonist for asthma', tags: ['asthma', 'allergy'] },
  { name: 'Maxpro 20mg', slug: 'maxpro-20mg', genericName: 'Esomeprazole', brand: 'Renata', manufacturer: 'Renata Limited', category: 'prescription-medicines', dosageForm: 'CAPSULE', strength: '20mg', packSize: '14 capsules', price: 154, discountPrice: 140, stockQty: 160, isPrescriptionRequired: true, isFeatured: true, shortDescription: 'Esomeprazole for acid reflux and ulcers', tags: ['ulcer', 'gerd'] },
  { name: 'Azithromycin 500mg (Azith)', slug: 'azith-500', genericName: 'Azithromycin', brand: 'Incepta', manufacturer: 'Incepta Pharmaceuticals', category: 'prescription-medicines', dosageForm: 'TABLET', strength: '500mg', packSize: '3 tablets', price: 75, stockQty: 200, isPrescriptionRequired: true, isFeatured: false, shortDescription: 'Macrolide antibiotic for bacterial infections', tags: ['antibiotic', 'infection'] },
  { name: 'Amlodipine 5mg (Amlopin)', slug: 'amlopin-5', genericName: 'Amlodipine', brand: 'Square', manufacturer: 'Square Pharmaceuticals', category: 'prescription-medicines', dosageForm: 'TABLET', strength: '5mg', packSize: '10 tablets', price: 40, stockQty: 300, isPrescriptionRequired: true, isFeatured: false, shortDescription: 'Calcium channel blocker for hypertension', tags: ['hypertension', 'bp'] },
  { name: 'Ciprocin 500mg', slug: 'ciprocin-500', genericName: 'Ciprofloxacin', brand: 'Square', manufacturer: 'Square Pharmaceuticals', category: 'prescription-medicines', dosageForm: 'TABLET', strength: '500mg', packSize: '10 tablets', price: 55, stockQty: 180, isPrescriptionRequired: true, isFeatured: false, shortDescription: 'Fluoroquinolone antibiotic', tags: ['antibiotic', 'uti', 'infection'] },
  { name: 'Losartan 50mg (Losar)', slug: 'losar-50', genericName: 'Losartan Potassium', brand: 'Healthcare', manufacturer: 'Healthcare Pharmaceuticals', category: 'prescription-medicines', dosageForm: 'TABLET', strength: '50mg', packSize: '10 tablets', price: 50, stockQty: 220, isPrescriptionRequired: true, isFeatured: false, shortDescription: 'ARB for hypertension management', tags: ['hypertension', 'bp'] },
  { name: 'Pantonix 40mg', slug: 'pantonix-40', genericName: 'Pantoprazole', brand: 'Beximco', manufacturer: 'Beximco Pharmaceuticals', category: 'prescription-medicines', dosageForm: 'TABLET', strength: '40mg', packSize: '14 tablets', price: 112, stockQty: 170, isPrescriptionRequired: true, isFeatured: false, shortDescription: 'PPI for acid-related disorders', tags: ['gastric', 'ppi'] },
  { name: 'Otidex Ear Drops', slug: 'otidex-ear-drops', genericName: 'Neomycin + Polymyxin B + Dexamethasone', brand: 'Opsonin', manufacturer: 'Opsonin Pharma', category: 'prescription-medicines', dosageForm: 'DROPS', strength: '5ml', packSize: '5ml dropper bottle', price: 70, stockQty: 90, isPrescriptionRequired: true, isFeatured: false, shortDescription: 'Antibiotic ear drops for ear infections', tags: ['ear', 'infection', 'drops'] },
  { name: 'Finix 20mg', slug: 'finix-20mg', genericName: 'Piroxicam', brand: 'Square', manufacturer: 'Square Pharmaceuticals', category: 'prescription-medicines', dosageForm: 'CAPSULE', strength: '20mg', packSize: '10 capsules', price: 60, stockQty: 140, isPrescriptionRequired: true, isFeatured: false, shortDescription: 'NSAID for pain and inflammation', tags: ['pain', 'arthritis', 'nsaid'] },
  { name: 'Atorvastatin 10mg (Atorva)', slug: 'atorva-10', genericName: 'Atorvastatin', brand: 'Incepta', manufacturer: 'Incepta Pharmaceuticals', category: 'prescription-medicines', dosageForm: 'TABLET', strength: '10mg', packSize: '10 tablets', price: 60, stockQty: 200, isPrescriptionRequired: true, isFeatured: false, shortDescription: 'Statin for cholesterol management', tags: ['cholesterol', 'statin'] },

  // Vitamins
  { name: 'Xinc B Syrup', slug: 'xinc-b-syrup', genericName: 'Zinc + B-Complex', brand: 'Square', manufacturer: 'Square Pharmaceuticals', category: 'vitamins-supplements', dosageForm: 'SYRUP', strength: '100ml', packSize: '100ml bottle', price: 95, stockQty: 220, isPrescriptionRequired: false, isFeatured: true, shortDescription: 'Zinc and B-Complex supplement syrup', tags: ['zinc', 'vitamin', 'immunity'] },
  { name: 'Ceevit 250mg', slug: 'ceevit-250mg', genericName: 'Ascorbic Acid (Vitamin C)', brand: 'Square', manufacturer: 'Square Pharmaceuticals', category: 'vitamins-supplements', dosageForm: 'TABLET', strength: '250mg', packSize: '30 tablets', price: 60, stockQty: 350, isPrescriptionRequired: false, isFeatured: true, shortDescription: 'Vitamin C tablet for immunity', tags: ['vitamin c', 'immunity'] },
  { name: 'Bexitol', slug: 'bexitol', genericName: 'Vitamin B-Complex', brand: 'ACI', manufacturer: 'ACI Limited', category: 'vitamins-supplements', dosageForm: 'TABLET', strength: 'B-Complex', packSize: '30 tablets', price: 45, stockQty: 280, isPrescriptionRequired: false, isFeatured: false, shortDescription: 'B-Complex vitamin supplement', tags: ['vitamin b', 'energy'] },
  { name: 'Calbo-D', slug: 'calbo-d', genericName: 'Calcium Carbonate + Vitamin D3', brand: 'Square', manufacturer: 'Square Pharmaceuticals', category: 'vitamins-supplements', dosageForm: 'TABLET', strength: '500mg + 200IU', packSize: '30 tablets', price: 180, stockQty: 200, isPrescriptionRequired: false, isFeatured: false, shortDescription: 'Calcium and Vitamin D supplement', tags: ['calcium', 'vitamin d', 'bone'] },
  { name: 'Ferocit', slug: 'ferocit', genericName: 'Ferrous Fumarate + Folic Acid', brand: 'Healthcare', manufacturer: 'Healthcare Pharmaceuticals', category: 'vitamins-supplements', dosageForm: 'TABLET', strength: '200mg + 0.5mg', packSize: '30 tablets', price: 65, stockQty: 250, isPrescriptionRequired: false, isFeatured: false, shortDescription: 'Iron and folic acid supplement', tags: ['iron', 'folic acid', 'anemia'] },
  { name: 'Cevit Plus', slug: 'cevit-plus', genericName: 'Multivitamin + Multimineral', brand: 'Square', manufacturer: 'Square Pharmaceuticals', category: 'vitamins-supplements', dosageForm: 'TABLET', strength: 'Multivitamin', packSize: '30 tablets', price: 150, discountPrice: 135, stockQty: 300, isPrescriptionRequired: false, isFeatured: true, shortDescription: 'Complete multivitamin and mineral supplement', tags: ['multivitamin', 'wellness'] },

  // Baby Care
  { name: 'Paracetamol Syrup (Ace)', slug: 'ace-syrup', genericName: 'Paracetamol', brand: 'Square', manufacturer: 'Square Pharmaceuticals', category: 'baby-care', dosageForm: 'SYRUP', strength: '120mg/5ml', packSize: '60ml bottle', price: 30, stockQty: 300, isPrescriptionRequired: false, isFeatured: true, shortDescription: 'Paracetamol syrup for children', tags: ['children', 'fever', 'baby'] },
  { name: 'Zinc Syrup', slug: 'zinc-syrup', genericName: 'Zinc Sulphate', brand: 'Eskayef', manufacturer: 'Eskayef Pharmaceuticals', category: 'baby-care', dosageForm: 'SYRUP', strength: '20mg/5ml', packSize: '100ml bottle', price: 50, stockQty: 250, isPrescriptionRequired: false, isFeatured: false, shortDescription: 'Zinc supplement for children with diarrhea', tags: ['zinc', 'baby', 'diarrhea'] },
  { name: 'MamyPoko Pants M', slug: 'mamypoko-pants-m', genericName: 'Baby Diaper', brand: null, manufacturer: 'Unicharm', category: 'baby-care', dosageForm: 'OTHER', strength: 'M (7-12 kg)', packSize: '40 pcs', price: 850, discountPrice: 790, stockQty: 100, isPrescriptionRequired: false, isFeatured: true, shortDescription: 'Pant-style baby diaper for active babies', tags: ['diaper', 'baby'] },

  // Diabetes Care
  { name: 'Metformin 500mg (Comet)', slug: 'comet-500', genericName: 'Metformin Hydrochloride', brand: 'Square', manufacturer: 'Square Pharmaceuticals', category: 'diabetes-care', dosageForm: 'TABLET', strength: '500mg', packSize: '10 tablets', price: 25, stockQty: 350, isPrescriptionRequired: true, isFeatured: false, shortDescription: 'Oral antidiabetic for type 2 diabetes', tags: ['diabetes', 'metformin'] },
  { name: 'Glimepiride 2mg (Amaryl)', slug: 'amaryl-2', genericName: 'Glimepiride', brand: 'Sanofi', manufacturer: 'Sanofi Bangladesh', category: 'diabetes-care', dosageForm: 'TABLET', strength: '2mg', packSize: '10 tablets', price: 80, stockQty: 120, isPrescriptionRequired: true, isFeatured: false, shortDescription: 'Sulfonylurea for type 2 diabetes', tags: ['diabetes', 'glimepiride'] },

  // Healthcare Devices
  { name: 'Digital Glucometer', slug: 'digital-glucometer', genericName: 'Blood Glucose Monitor', brand: null, manufacturer: 'Accu-Chek / Roche', category: 'healthcare-devices', dosageForm: 'DEVICE', strength: 'N/A', packSize: '1 unit + 10 strips', price: 1500, discountPrice: 1350, stockQty: 30, isPrescriptionRequired: false, isFeatured: true, shortDescription: 'Digital blood glucose monitoring system', tags: ['glucometer', 'diabetes', 'device'] },
  { name: 'Nebulizer Machine', slug: 'nebulizer-machine', genericName: 'Compressor Nebulizer', brand: null, manufacturer: 'Omron Healthcare', category: 'healthcare-devices', dosageForm: 'DEVICE', strength: 'N/A', packSize: '1 unit', price: 3500, discountPrice: 3200, stockQty: 15, isPrescriptionRequired: false, isFeatured: true, shortDescription: 'Compressor nebulizer for respiratory therapy', tags: ['nebulizer', 'asthma', 'device'] },
  { name: 'Digital Blood Pressure Monitor', slug: 'digital-bp-monitor', genericName: 'Blood Pressure Monitor', brand: null, manufacturer: 'Omron Healthcare', category: 'healthcare-devices', dosageForm: 'DEVICE', strength: 'N/A', packSize: '1 unit', price: 2800, discountPrice: 2500, stockQty: 25, isPrescriptionRequired: false, isFeatured: false, shortDescription: 'Automatic upper arm blood pressure monitor', tags: ['bp', 'blood pressure', 'device'] },

  // Personal Care
  { name: 'Cetaphil Gentle Skin Cleanser', slug: 'cetaphil-cleanser', genericName: 'Gentle Skin Cleanser', brand: null, manufacturer: 'Galderma', category: 'personal-care', dosageForm: 'SOLUTION', strength: '250ml', packSize: '250ml bottle', price: 890, discountPrice: 830, stockQty: 60, isPrescriptionRequired: false, isFeatured: false, shortDescription: 'Gentle non-irritating skin cleanser', tags: ['skincare', 'cleanser'] },

  // First Aid
  { name: 'Savlon Antiseptic', slug: 'savlon-antiseptic', genericName: 'Chlorhexidine + Cetrimide', brand: 'ACI', manufacturer: 'ACI Limited', category: 'first-aid', dosageForm: 'SOLUTION', strength: '56ml', packSize: '56ml bottle', price: 55, stockQty: 180, isPrescriptionRequired: false, isFeatured: false, shortDescription: 'Antiseptic liquid for wound cleaning', tags: ['antiseptic', 'first aid', 'wound'] },
  { name: 'Dettol Antiseptic', slug: 'dettol-antiseptic', genericName: 'Chloroxylenol', brand: null, manufacturer: 'Reckitt Benckiser', category: 'first-aid', dosageForm: 'SOLUTION', strength: '60ml', packSize: '60ml bottle', price: 65, stockQty: 200, isPrescriptionRequired: false, isFeatured: false, shortDescription: 'Antiseptic disinfectant liquid', tags: ['antiseptic', 'disinfectant', 'dettol'] },

  // Sexual Wellness
  { name: 'Durex Extra Thin', slug: 'durex-extra-thin', genericName: 'Latex Condom', brand: null, manufacturer: 'Reckitt Benckiser', category: 'sexual-wellness', dosageForm: 'OTHER', strength: 'N/A', packSize: '3 pcs', price: 180, stockQty: 100, isPrescriptionRequired: false, isFeatured: false, shortDescription: 'Ultra-thin latex condom', tags: ['condom', 'contraception'] },

  // Ayurvedic
  { name: 'Hamdard Rooh Afza', slug: 'rooh-afza', genericName: 'Herbal Drink Concentrate', brand: null, manufacturer: 'Hamdard Laboratories', category: 'ayurvedic-herbal', dosageForm: 'SYRUP', strength: '750ml', packSize: '750ml bottle', price: 250, stockQty: 80, isPrescriptionRequired: false, isFeatured: false, shortDescription: 'Traditional herbal cooling drink', tags: ['herbal', 'drink', 'ayurvedic'] },
];
