export const settingsSeedData = {
  storeName: 'PharmaNest BD',
  supportPhone: '01700000000',
  supportEmail: 'support@pharmanest.com.bd',
  storeAddress: 'House 12, Road 5, Dhanmondi, Dhaka-1205',
  bkashNumber: '01XXXXXXXXX',
  nagadNumber: '01XXXXXXXXX',
  rocketNumber: '01XXXXXXXXXXX',
  codEnabled: true,
  baseDeliveryCharge: 60,
  dhakaDeliveryCharge: 60,
  outsideDhakaCharge: 120,
  freeDeliveryThreshold: 500,
  prescriptionPolicyText: 'Prescription medicines require a valid prescription from a licensed doctor. Our pharmacist will review your prescription before processing.',
  footerText: 'Your trusted online pharmacy in Bangladesh. Genuine medicines delivered to your door.',
};
